// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/adapters/bank (interfaces: Adapter)
//
// Generated by this command:
//
//	mockgen -destination mocks/mock_adapter.go -package mocks github.com/cko-recruitment/payment-gateway-challenge-go/internal/adapters/bank Adapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockAdapter) ProcessPayment(ctx context.Context, req models.BankRequest) (models.BankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, req)
	ret0, _ := ret[0].(models.BankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockAdapterMockRecorder) ProcessPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockAdapter)(nil).ProcessPayment), ctx, req)
}
